### ISSUE TITLE
Fix button margin in counsel buttons

### ISSUE THREAD

**Issue by junhoyeo** [dimigoin/dimigoin-front#159]
<img width="1552" alt="스크린샷 2019-03-13 오후 12 41 29" src="https://user-images.githubusercontent.com/32605822/54252261-78bf0280-458d-11e9-9c11-aecd3dbc6bca.png">

위와 같이 PC에서 두 버튼 사이에 horizontal margin이 없습니다.

<img alt="dimigo in_request_counsel(iPhone 6_7_8)" src="https://user-images.githubusercontent.com/32605822/54252290-883e4b80-458d-11e9-9579-9b1980bc7a4d.png" width="70%"/>

모바일에서는 두 버튼 간 vertical margin이 필요합니다.

**Comment by a1p4ca** [comment]
원래 ButtonGroup 컴포넌트를 썼어야 했는데 누가 멋대로 바꾼거라 마진보단 컴포넌트 교체가 필요해요

**Comment by junhoyeo** [comment]
> 원래 ButtonGroup 컴포넌트를 썼어야 했는데 누가 멋대로 바꾼거라 마진보단 컴포넌트 교체가 필요해요

ButtonGroup 컴포넌트를 적용시켜 봤는데, 텍스트 양이 너무 많아서 부자연스러워 보이네요.

**Comment by a1p4ca** [comment]
제플인 디자인 확인해보셨나요? 디미루에 있는 기존 버튼그룹 컴포넌트랑 여기서 쓰는 버튼그룹이랑 달라요. 새로 개발해야돼요.

**Comment by junhoyeo** [comment]
> 제플인 디자인 확인해보셨나요? 디미루에 있는 기존 버튼그룹 컴포넌트랑 여기서 쓰는 버튼그룹이랑 달라요. 새로 개발해야돼요.

앗 죄송합니다! 확인했습니다. 컴포넌트 이름은 `DimiLongButtonGroup`이 어떨까 싶은데, 너무 긴가요?
