### ISSUE TITLE
fix(service): renew career counsel to employment counsel

### ISSUE THREAD

**Issue by a1p4ca** [dimigoin/dimigoin-front#164]
2018년에 남승완 선생님의 요청으로 만들어진 상담 신청이 사실상 작년에도 쓰이지 않았던 것으로 생각되고, 올해는 교감이 되시면서 상담을 계속하실지 의문입니다.

**Comment by taehoon02** [comment]
우선 이번주부터 1, 2타임만 운영하되, 3타임으로 나누는 것은 추후에 결정합니다. 이슈는 닫지 않습니다.

**Comment by gliserin** [comment]
**바꿔야하는 내용**

취업 상담은 이미순 취업지원관 선생님께서 진행하는 상담으로 매주 월요일, 화요일에 상담 신청자에 한하여 신관 IT부서에서 진행됩니다.

신청방법
아래의 항목에서 원하는 일시에 상담을 신청하고, 상담하고 싶은 주제 혹은 내용에 대해 아래의 이메일 주소로 메일을 보냅니다!
- 상담 내용 이메일 주소 : soon040821@naver.com


바꿔야할 코드

현재  수, 금요일 -> 월, 화요일

시간대 : 월, 화 각 5회
10:00 ~ 10:50
11:00 ~ 11:50
12:00 ~ 12:50
13:50 ~ 14:40
14:50 ~ 15:40

**Comment by taehoon02** [comment]
진로 상담이 취업 상담으로 변경된 것인가요?

**Comment by hd1534** [comment]
백엔드 크론 바꾸었습니다.
