### ISSUE TITLE
Can't set assignment's deadline

### ISSUE THREAD

**Issue by uhmtoto** [dimigoin/dimigoin-front#165]
<img width="1367" alt="스크린샷 2019-03-17 15 28 36" src="https://user-images.githubusercontent.com/16954420/54486285-73352580-48c9-11e9-8fdc-fd0a8071f89c.png">

과제 마감기한 설정이 되지 않고 무조건 1970년 1월 19일로 설정됩니다.

**Comment by hd1534** [comment]
그거 프론트는 unixtime 이고 백엔드는 datetime이라...
백에서 수정할거라 ㄱㄷㄱㄷ

**Comment by uhmtoto** [comment]
넴

**Comment by hd1534** [comment]
백인줄 알았는데 다시 확인해보니 프론트네;;
일단 이건 태훈이가 함
