### ISSUE TITLE
Refactor Service: Ingang

### ISSUE THREAD

**Issue by taehoon02** [dimigoin/dimigoin-front#168]
1학년은 야자 1, 2타임 1주당 티켓 4개 / 하루 최대 2번
2학년은 야자 1, 2, 3타임 1주당 티켓 5개 / 하루 최대 2번

방과후 신청 추가하는 것처럼 만들어야 합니다.
매일 새로운 인강실을 자동으로 생성하고 요일별 반복도 설정할 수 있어야 합니다.

**Comment by taehoon02** [comment]
1학년은 야자 1, 2타임 1주당 티켓 4개
2학년은 야자 1, 2, 3타임 1일당 티켓 1개 입니다.

**Comment by a1p4ca** [comment]
티켓 개수는 프론트에서 다루지 마세요. 항상 백엔드에서 최대티켓과 남은 티켓 개수를 넘겨받으세요.
