### ISSUE TITLE
Zeze's 要請文

### ISSUE THREAD

**Issue by hjh010501** [dimigoin/dimigoin-front#17]
- [ ] 인강실 신청 페이지 들어갈 때 인강실 공지 창 띄우게 하기
- [x] 공지사항 등록 관리자 페이지
- [ ] dimigoincon 디스코드에 있는 아이콘으로 업데이트

**Comment by a1p4ca** [comment]
인강실 공지는 이제 필요없나요?

**Comment by hjh010501** [comment]
notion 에 다 적어논거라 닫았습니다
