### ISSUE TITLE
API docs for mentoring

### ISSUE THREAD

**Issue by hd1534** [dimigoin/dimigoin-front#195]
## **[GET] /mentor**
JWT로 선생님 본인의 멘토링 상황을 볼 수 있다.
**Response**
```
{
  "mentors": [ // 상담 타임별로 같은선생님이라도 여러개
    {
      "idx": 0,
      "day": "string", // 상담 요일
      "date": 0, // 상담 날짜 (유닉스타임)
      "start_time" : "00:00",  //24시 표기
      "end_time" : "00:00",  //24시 표기
      "subject": "string", // 선생님 과목
      "target_grade": 1, // 멘토링 학년
      "room": "string", // 상담 교실
      "max_user": 0, //최대 인원
      "mentoring_request": [ // 멘토 신청자
        {
          "idx": 0, // request_idx
          "requester": { // 신청자
            "idx": 0,
            "name": "string",
            "grade": 0,
            "klass": 0,
            "number": 0,
            "serial":  0
          }
        }
      ]
    }
  ]
}
```

## **[POST] /mentor**

JWT Token 으로 선생님 user_idx 와 이름을 구해서 넣음

**Payload**
```
{
  "day": "string",
  "subject": "string",
  "room": "string",
  "target_grade": 0,
  "start_time" : "00:00",  //24시 표기
  "end_time" : "00:00"  //24시 표기
  "max_user": 0, //최대 인원
}
```

## **[DELETE] /mentor/{mentor_idx}**

JWT Token 으로 선생님 본인만이 자신의 멘토링을 지울 수있음.

## **[GET] /mentor/admin**
관리자에게 모든 멘토링 목록을 보여줌
**Response**
```
{
  "mentors": [ // 상담 타임별로 같은선생님이라도 여러개
    {
      "idx": 0,
      "day": "string", // 상담 요일
      "date": 0, // 상담 날짜 (유닉스타임)
      "start_time" : "00:00",  //24시 표기
      "end_time" : "00:00",  //24시 표기
      "subject": "string", // 선생님 과목
      "teacher": { // 선생님
        "idx": 0, // 선생님 user_idx
        "name": "string" // 선생님 성함
      },
      "target_grade": 1, // 멘토링 학년
      "request_start_date": 0, // 신청 시작 시간(유닉스 타임)
      "request_end_date": 0, // 신청 마감 시간(유닉스 타임)
      "room": "string", // 상담 교실
      "max_user": 0, //최대 인원
      "mentoring_request": [ // 멘토 신청자
        {
          "idx": 0, // request_idx
          "request_time": "string", // 신청시각
          "requester": { // 신청자
            "idx": 0,
            "name": "string",
            "grade": 0,
            "klass": 0,
            "number": 0,
            "serial": 0
          }
        }
      ]
    }
  ]
}
```

## **[POST] /mentor/admin**

관리자가 추가

**Payload**
```
{
  "teacher_name": "string",
  "day": "string",
  "subject": "string",
  "room": "string",
  "target_grade": 0,
  "start_time" : "00:00",  //24시 표기
  "end_time" : "00:00"  //24시 표기
  "max_user": 0, //최대 인원
}
```

## **[DELETE] /mentor/admin/{mentor_idx}**

관리자가 해당 멘토링을 삭제할 수 있음.

## **[GET] /mentor/request**
자신이 신청할 수 있는 목록

JWT Token을 받아 자신의 학년에 맞게 줌

**Response**
```
{
  "mentors": [
    {
      "idx": 0,
      "day": "string", // 상담 요일
      "date": 0, // 상담 날짜 (유닉스타임)
      "start_time" : "00:00",  //24시 표기
      "end_time" : "00:00",  //24시 표기
      "subject": "string", // 선생님 과목
      "teacher": { // 선생님
        "idx": 0, // 선생님 user_idx
        "name": "string" // 선생님 성함
      }
      "request_start_date": 0, // 신청 시작 시간 (유닉스 타임)
      "request_end_date": 0, // 신청 마감 시간 (유닉스타임)
      "room": "string", // 상담 교실
      "status": true,  //자신의 신청여부
      "present": 0,  //현재 신청된 인원
      "max_user": 0, //최대 인원
    }
  ]
}
```

## **[POST] /mentor/request/{mentor_idx}**

JWT Token 으로 신청

## **[DELETE] /mentor/request/{mentor_idx}**

JWT Token 으로 신청 취소

## **[POST] /mentor/notice**

관리자일 경우 새로운 공지 추가

**Payload**
```
{
  "description": "string"  //내용
}
```

## **[GET] /mentor/notice**

최신 공지 불러오기

**Response**
```
{
  "description": "string"  //내용
}
```

## **[POST] /mentor/cron
	
일주일 단위로 크론잡을 위해 (curl)
아마도 프론트는 쓸일 없을거..

* * *
이상한거나 필요한거 있으면 말좀

**Comment by junhoyeo** [comment]
확인했는데 디자인에서는 한 날짜에 대해서 여러 가지 시간 옵션을 선택할 수 있게 하는 식으로 약간 다른 것 같아요!

<img width="80%" alt="스크린샷 2019-03-27 오후 10 57 07" src="https://user-images.githubusercontent.com/32605822/55119131-142aa880-5134-11e9-9d2e-e170617c0ac4.png">

**Comment by junhoyeo** [comment]
멘토링 공지사항 관련 API도 안내해주시면 감사하겠습니다.

**Comment by hd1534** [comment]
## **[POST] /mentor/notice**

관리자일 경우 새로운 공지 추가

**Payload**
```
{
  "description": "string"  //내용
}
```

## **[GET] /mentor/notice**

최신 공지 불러오기

**Response**
```
{
  "description": "string"  //내용
}
```

이런식으로 할것 같아

**Comment by junhoyeo** [comment]
오오 감사합니다! 혹시 mentor의 `time`에 대해서도 설명해 주실 수 있을까요? ㅜㅜ

**Comment by junhoyeo** [comment]
> 오오 감사합니다! 혹시 mentor의 `time`에 대해서도 설명해 주실 수 있을까요
> 상담 타임이라고 되어 있는데 잘 모르겠네요

유닉스타임 string으로 `start_time`, `end_time` 들어옴

**Comment by hd1534** [comment]
time 대신에 start_time, end_time 두개를 주고, 
"start_time" : "00:00",  //24시 표기 (string)
"end_time" : "00:00"  //24시 표기 (string)
이런식으로 줄거야

**Comment by hd1534** [comment]
max_user 같은거 사소하게 수정한거 좀 있으니 확인좀

**Comment by hd1534** [comment]
max보다 넘는거 403 띠우는거랑 신청기간 확인하는거 아직 안함
자고나서 할거임

**Comment by junhoyeo** [comment]
**[GET] /mentor/notice**에서 아래와 같은 오류가 발생합니다.
https://dev-api.dimigo.in/mentor/notice
{"message": "'NoneType' object has no attribute 'idx'"}

**Comment by junhoyeo** [comment]
**[GET] /mentor/notice**
```json
{"message": "Unable to marshal field \"date\" value \"1554044400.0\": Unsupported DateTime format"}
```

**[GET] /mentor/admin**
```json
{"message": "'NoneType' object is not subscriptable"} 
```

**Comment by uhmtoto** [comment]
delete에서 [DELETE] /mentor/admin/{mentor_idx}이랑
[DELETE] /mentor/{mentor_idx}. 이 왜 나눠져있는건가요?
