### ISSUE TITLE
내일 아침, 야외점호를 할 가능성 보여주기

### ISSUE THREAD

**Issue by a1p4ca** [dimigoin/dimigoin-front#3]
날씨 정보를 통해 식 유도
1년동안 야외점호한 날의 데이터셋이 있으면 더 정확하게 구할 수 있을 것 같기도 하고

**Comment by a1p4ca** [comment]
오늘 야외점호를 했는지 안 했는지 학생들한테 정보를 입력받아서 데이터셋을 모을 수는 있을 것 가틈

**Comment by hjh010501** [comment]
3월 ~ 4월, 미세먼지랑 시험기간같은 예외도 처리해야할듯

**Comment by a1p4ca** [comment]
그런거에 다 가중치 부여해서 계산해야지 ㅇㅇ

**Comment by a1p4ca** [comment]
Too low priority
