### ISSUE TITLE
gitbook에서 사진이 안보이는 문제

### ISSUE THREAD

**Issue by AkiaCode** [dimigoin/dimigoin-front#386]
`gitbook`에서 모든 사진들이 이렇게 나옵니다

![image](https://user-images.githubusercontent.com/71239005/98772993-4e40df00-242b-11eb-9129-d6a2b6c65c81.png)

**Comment by rycont** [comment]
안녕하세요 프론트엔드 개발자 정한입니다! 전 개발자님들께 깃북 관리권한을 위임받지 못해서 오류 수정은 힘들것같습니다. 또한 리뉴얼될 디미고인의 문서를 공개할 계획은 아직 없습니다.

**Comment by AkiaCode** [comment]
알겠습니다.
