### ISSUE TITLE
잘못된 혹은 만료된 액세스 토큰을 보유하고 있을 경우에 대한 예외처리 필요

### ISSUE THREAD

**Issue by a1p4ca** [dimigoin/dimigoin-front#5]
현재는 해당 로직이 구현되어 있지 않기 때문에, 잘못된 토큰을 가지고 있어도 자동 로그아웃이 되지 않습니다.

**Comment by hjh010501** [comment]
사이트 접속할 때 마다 토큰
[GET] /user/jwt/ 
으로 쏴서 200 안뜨면 로그아웃 시켜주세요

### **이거 9월에 달린 이슈인데 ㅠㅠ 빨리 처리해주세요 ㅠㅠ**

**Comment by a1p4ca** [comment]
/user/jwt 를 왜 만들었어요
그냥 모든 요청에 훅 걸어놓고 만료된 토큰이면 로그아웃하면 되는데

**Comment by a1p4ca** [comment]
그리고 우리 JWT 토큰 정석대로 리프레쉬 토큰 / 액세스 토큰 방식으로 안 바꾸나요?

**Comment by hjh010501** [comment]
1. 원래 만든이유는 안드로이드쪽에서 jwt 까기 귀찮다구 만들어줬어요 웹에서 쓰려는게 아니라 그래서 저거써도 되고 아님 notice 불러올때 안나오면 로그아웃하면 되고 

2. refresh token 방식으로 바꾸면 백엔드가 일해야되서 싫어오😭

**Comment by a1p4ca** [comment]
와 jwt 까는게 뭐가 귀찮다고 api 요청 때리는게 더 귀찮을 듯; @wj1187

**Comment by wj1187** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 안드에서 ㅈㄴ 귀찮음;;

**Comment by a1p4ca** [comment]
. 기준으로 split 하고 마지막 요소 base64 디코딩하면 되는데..

**Comment by a1p4ca** [comment]
Closed by 798a04c, 7aeb6a6, d609c74
