### ISSUE TITLE
동아리 신청 페이지 이슈

### ISSUE THREAD

**Issue by hjh010501** [dimigoin/dimigoin-front#55]
### 동아리 신청 기간 이슈
현재 디미고인 동아리 신청 페이지는 old 한 api 기준으로 작성되어있습니다.
기존 circle json response 에서 apply_start_date 와 apply_end_date 가 모두 삭제되었으며, 이는 모두 config API 를 통해 동아리 신청 및 마감 기간을 불러오도록 하였습니다.

### 동아리 합격 이후 최종 버튼
현재 디미고인 동아리 신청 마지막 과정 중 신청자에게 최종 버튼의 위치가 신청 / 취소 버튼이 있는 다이얼로그 창이 아닌 circle 카드 창에만 나와있습니다.

### 그 외 간단한 요구사항

- [ ] 자기소개 칸 line-height 증가
- [ ] 타이틀 "2019년 동아리 가입 신청🚀" → "동아리 가입 신청"

**Comment by a1p4ca** [comment]
이슈를 작은 단위로 나눠주세요.
이 이슈의 경우

* API payload has changed
* 동아리 신청에서 최종 결정 버튼이 모달에 없습니다
* 동아리 신청 관련 세부 UI 수정 요청

로 나눌 수 있겠네요. 이 이슈는 닫고 새롭게 추가바랍니다.

**Comment by a1p4ca** [comment]
나머지 이슈(#56, #57, #58)들도 마찬가지입니다. TODO 리스트는 이슈가 아니라 PR에 명시하는 것이 더 적절해 보입니다. 이슈의 경우 TODO 항목별로 하나의 이슈가 있는 것이 적절할 것 같습니다.

**Comment by a1p4ca** [comment]
덧붙이자면 단순한 텍스트 변경과 같은 마이너한 UI Fix(#56)와 추가 기능 개발(비즈니스 로직)이 요구되는 UI Update(#58)은 분리해주셔야 관리가 수월합니디.

**Comment by hjh010501** [comment]
TO-DO 는 모두 PR (#45) 로 옮겼으며 작은 단위로 나눴습니다 (#60, #61)

**Comment by a1p4ca** [comment]
보통 한 PR당 한 이슈 닫는게 원칙이고 저 이슈 같은 경우는 대규모 리팩토링이기 때문에 연관된 이슈들도 함께 처리하려고 저렇게 목록 작성했던거지 서로 관련도 없는 그  많은 작업들을 한번에 처리하려고 TODO 리스트를 작성한 것이 아닙니다. 애초에 그럴거였으면 브랜치를 안 나누고 그냥 readme에 todo 넣고 마스터에 바로바로 커밋하지 왜 굳이? 왜 이슈를 만들고 브랜치를 생성해서 PR을 하는건지 생각해주세요.
PR에 넣는 TODO 리스트는 다루고 있는 한가지 이슈에 대한 로드맵을 작게 쪼개서 작성하는겁니다.

**Comment by a1p4ca** [comment]
해당 PR과 관련된 문제가 아니라면 뭘 해달라고 요구하는 커멘트 남기지 마세요. 하나의 PR은 한가지 목적만 필요합니다.

**Comment by a1p4ca** [comment]
따라서 https://github.com/dimigoin/dimigoin-front/pull/45#issuecomment-465689239 는 새로운 이슈로 다시 옮겨주세요.

**Comment by hjh010501** [comment]
> 나머지 이슈(#56, #57, #58)들도 마찬가지입니다. TODO 리스트는 이슈가 아니라 PR에 명시하는 것이 더 적절해 보입니다.

이 말을 기존 PR 있는거에 추가 기능 요구 느낌으로 올리라는 말로 오해했네요 다시 수정할께여
