### ISSUE TITLE
Minor UI changes in Afterschool Request

### ISSUE THREAD

**Issue by hjh010501** [dimigoin/dimigoin-front#56]
* 1, 2, 3 ... 교시에서 월 화 수 목 금 원래대로 바꾸기
* 타이틀 "2018년 ⛷겨울방학☃ 방과 후 활동 신청" → "방과 후 활동 신청"

**Comment by a1p4ca** [comment]
https://github.com/dimigoin/dimigoin-front/issues/55#issuecomment-465381177 에 이 이슈를 언급하기는 했지만 이 이슈는 작은 UI 수정이기 때문에 제목만 바꾸도록 하겠습니다.

**Comment by junhoyeo** [comment]
revert 하면서 수정되지 않았습니다.
