### ISSUE TITLE
인강실 신청 페이지 이슈

### ISSUE THREAD

**Issue by hjh010501** [dimigoin/dimigoin-front#57]
### 인강실 신청 페이지 이슈
현재 가장 고쳐야 할 점이 많은 인강실 신청 페이지입니다.
기존 Javascript array 로 보내주던 인강 response 를 json 으로 변경하였습니다.

### To-do
- [ ] 인강실 신청 페이지 들어갈 때 인강실 공지 창 띄우기

**Comment by a1p4ca** [comment]
인강실 신청은 백엔드와 함께 리팩토링 작업이 필요합니다. 본 이슈는 제가 새로 작성하겠습니다.
