### ISSUE TITLE
"최종 결정 버튼" doesn't exist in circle modal

### ISSUE THREAD

**Issue by hjh010501** [dimigoin/dimigoin-front#61]
## 동아리 합격 이후 최종 버튼

현재 디미고인 동아리 신청 마지막 과정 중 신청자에게 최종 버튼의 위치가 신청 / 취소 버튼이 있는 모달 창이 아닌 circle 카드 창에만 나와있습니다.

**Comment by a1p4ca** [comment]
불필요하다고 생각합니다
