### ISSUE TITLE
Minor UI changes in Circle Request

### ISSUE THREAD

**Issue by hjh010501** [dimigoin/dimigoin-front#62]
*  자기소개 칸 line-height 증가
*  타이틀 "2019년 동아리 가입 신청🚀" → "동아리 가입 신청"

**Comment by junhoyeo** [comment]
- `line-height` 값은 어느 정도가 적당할까요? 
- `DimiLongInput` 컴포넌트 자체에서 수정하는 것이 좋을까요?

**Comment by junhoyeo** [comment]
revert 하면서 수정되지 않았습니다.
