### ISSUE TITLE
Minor UI changes in teacher afterschool management

### ISSUE THREAD

**Issue by hjh010501** [dimigoin/dimigoin-front#65]
- 타이틀 변경: "2018년 겨울방학 방과 후 활동 관리" → "방과 후 활동 신청 관리"

**Comment by taehoon02** [comment]
이슈 닫아주세요.

**Comment by a1p4ca** [comment]
Closed by sys1015

**Comment by a1p4ca** [comment]
Closed by #84

**Comment by taehoon02** [comment]
revert하면서 ui가 변경되지 않았습니다.

**Comment by junhoyeo** [comment]
> revert하면서 ui가 변경되지 않았습니다.

제대로 변경된 것 같습니다. 다시 확인 부탁드립니다.

**Comment by taehoon02** [comment]
이슈 닫겠습니다.
