### ISSUE TITLE
API payload has changed in afterschool

### ISSUE THREAD

**Issue by hjh010501** [dimigoin/dimigoin-front#69]
### 방과후 신청 API 변경
기존 API 에서는 request_start_date 와 request_end_date 둘 다 Datetime 에 맞추어 API 를 작동시켰다면, 지금은 Unix Timestamp 를 이용하여 시간을 정수 형태로 표현하고 있습니다. 따라서 다음 API 에 있는 request_start_date 와 request_end_date 둘의 value 를 integer 형식의 unix timestamp 로 변경하여 기능에 적용해주시길 바랍니다.

**request_start_date 와 request_end_date 는 방과후 신청 시작 시간, 마감 시간을 의미합니다.**

### [GET] /afterschools/student/

**Comment by taehoon02** [comment]
이미 afterschool은 unix-timestamp를 활용하여 unix timestamp를 사용하는 것 같습니다. 확인부탁드립니다. 참고로 assignment는 unix timestamp가 아닙니다.

**Comment by a1p4ca** [comment]
그러게요 https://github.com/dimigoin/dimigoin-front/commit/412c50dc4931c13b50bf2ad43b51f674441358da 여기서 바로 적용했어요. 함종현 백엔드 확인바람

**Comment by hjh010501** [comment]
백엔드에도 적용되어있읜 이슈 닫습니다.
