### ISSUE TITLE
Change max request count in afterschool same day

### ISSUE THREAD

**Issue by hjh010501** [dimigoin/dimigoin-front#70]
- 기존에는 한 요일에 최대 1개의 방과후 신청만을 가능하게 하였지만, 2019년에는 방과후를 한 요일에 2개씩 들을 수 있게 변경한다고 합니다.
- 프론트단에서는 `[GET] /afterschools/student/` 로 받아올때 특정 요일에 방과후 status 가 request 로 된게 2개일 경우 막아주시면 됩니다.
- 이는 나중에 확장성을 고려하여 요일당 최대 신청 방과후 갯수를 지정할 수 있게 관리자페이지에서 변경할 수 있게 하여야 하며 이는 시간관계상 나중에 진행 하는게 좋을 듯 싶습니다.

**Comment by gliserin** [comment]
3월 8일까지 마무리해야합니다.

**Comment by taehoon02** [comment]
일단 제제쌤 말씀대로 한 후, 나중에 확장성을 고려하여 신청 관리 페이지에서 방과후 개수를 수정할 수 있게 변경하도록 하겠습니다. @gliserin 확인부탁드립니다

**Comment by a1p4ca** [comment]
Closed by #109
