### ISSUE TITLE
API payload has changed in assignment

### ISSUE THREAD

**Issue by hjh010501** [dimigoin/dimigoin-front#71]
### 과제제출 API 변경
#69 와 동일하게 end_date 라는 과제 마감일이 Datetime 에서 Unix Timestamp 로 바뀌었습니다.

**Comment by taehoon02** [comment]
이슈 71번 유닉스 타임으로 제가 변경하고 PR 넣을게요. 오늘 오후쯤에 PR날리겠습니다.
