### ISSUE TITLE
Unintended bottom margin of meal group in main page

### ISSUE THREAD

**Issue by a1p4ca** [dimigoin/dimigoin-front#83]
![image](https://user-images.githubusercontent.com/13712304/53712843-fac37300-3e8b-11e9-8860-83c6cd9374a5.png)

제플린 참고

**Comment by junhoyeo** [comment]
[reset.scss](https://github.com/dimigoin/dimigoin-front/blob/master/app/scss/reset.scss) 89번째 줄 `margin: 0;` 없애면 해결되는 것 같네요

**Comment by a1p4ca** [comment]
그 파일 건들면 UI 전체가 깨져서 절대 수정하면 안돼요. 왜 그 파일이 있어야 하는지는 [여기](https://youtaekjung.github.io/2018/04/23/css/CSS-reset/) 참고

**Comment by junhoyeo** [comment]
> 그 파일 건들면 UI 전체가 깨져서 절대 수정하면 안돼요. 왜 그 파일이 있어야 하는지는 [여기](https://youtaekjung.github.io/2018/04/23/css/CSS-reset/) 참고

그렇다면 다른 솔루션을 찾아보겠습니다! 감사합니다

**Comment by a1p4ca** [comment]
정 모르겠으면 원래 저거 괜찮았는데 최근에 저렇게 된거니까 12월 정도 커밋부터 `git bisect` 명령어로 찾으면 문제되는 커밋 찾을 수 있을거에요

**Comment by a1p4ca** [comment]
이거 보니까 #86 여기서 같이 고치는게 맞는 것 같아서 닫을게요.
