### ISSUE TITLE
Wrong button layout at book request

### ISSUE THREAD

**Issue by uhmtoto** [dimigoin/dimigoin-front#95]
<img width="1440" alt="2019-03-06 20 56 06" src="https://user-images.githubusercontent.com/16954420/53879811-bd5d1200-4052-11e9-8312-887f1e9e2572.png">

맥 사파리에서만 도서 신청 버튼이 아래로 밀려서 나옵니다.

**Comment by a1p4ca** [comment]
Fixed in #100
